name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        eslint-version: 8

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install ESLint v${{ matrix.eslint-version }}
        run: yarn add eslint@^${{ matrix.eslint-version }} --dev

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Build
        run: yarn build
